# Generated by Django 4.2.7 on 2025-10-26 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('url_access', 'Acesso a URL'), ('app_launch', 'Abertura de Aplicativo'), ('window_change', 'Mudança de Janela'), ('copy_paste', 'Copiar/Colar'), ('screenshot', 'Screenshot Tentado'), ('system', 'Evento do Sistema')], max_length=20, verbose_name='Tipo de Evento')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='Navegador')),
                ('app_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do Aplicativo')),
                ('window_title', models.CharField(blank=True, max_length=500, verbose_name='Título da Janela')),
                ('machine_name', models.CharField(blank=True, max_length=200, verbose_name='Nome da Máquina')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='Dados Adicionais')),
                ('exam_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='students.examsession', verbose_name='Sessão de Exame')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Evento de Monitoramento',
                'verbose_name_plural': 'Eventos de Monitoramento',
                'db_table': 'monitoring_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Severidade')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('reviewing', 'Em Revisão'), ('resolved', 'Resolvido'), ('false_positive', 'Falso Positivo')], default='new', max_length=20, verbose_name='Status')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('reason', models.TextField(verbose_name='Motivo do Alerta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas do Administrador')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.monitoringevent', verbose_name='Evento')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='students.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitoringevent',
            index=models.Index(fields=['-timestamp'], name='monitoring__timesta_2ad7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringevent',
            index=models.Index(fields=['student', '-timestamp'], name='monitoring__student_34396e_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='monitoring__event_t_b82db3_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='alerts_created_6327ec_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='alerts_status_5c7524_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', '-created_at'], name='alerts_severit_03a0f3_idx'),
        ),
    ]
