# Generated by Django 4.2.7 on 2025-10-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringevent',
            name='key_event',
            field=models.CharField(blank=True, max_length=100, verbose_name='Evento de Tecla'),
        ),
        migrations.AlterField(
            model_name='monitoringevent',
            name='event_type',
            field=models.CharField(choices=[('url_access', 'Acesso a URL'), ('app_launch', 'Abertura de Aplicativo'), ('window_change', 'Mudança de Janela'), ('copy_paste', 'Copiar/Colar'), ('screenshot', 'Screenshot Tentado'), ('keyboard_event', 'Evento de Teclado'), ('system', 'Evento do Sistema')], max_length=20, verbose_name='Tipo de Evento'),
        ),
    ]
